name: Jekyll Themes
#url: http://matt.harzewski.com
url: http://ysj414.github.io
description: Insert tagline here

permalink: /themes/:title/
title: "Developer Yoonseon Jeong blog"

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
